version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=odapython3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      # TODO Fix up this path
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./wait-for-it.sh -h db -p 5432 -t 0 && python3 django/manage.py migrate && python3 django/manage.py setup_oda && gunicorn --workers=4 --chdir django -b 0.0.0.0:8001 oda.wsgi"
    environment:
      - DJANGO_SETTINGS_MODULE=oda.settings.development
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  socket:
    build:
      context: .
      dockerfile: Dockerfile.socketapp
    command: bash -c "npm install && npm start"
    volumes:
      - .:/code
      - /code/socketapp/node_modules
    ports:
      - "8080:8080"
